# Generated by Django 4.2 on 2025-12-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.TextField(blank=True, help_text='Détails complets du service (liste à puces, etc.)', verbose_name='Détails complets'),
        ),
        migrations.AddField(
            model_name='service',
            name='featured',
            field=models.BooleanField(default=False, verbose_name="En vedette (page d'accueil)"),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Description courte'),
        ),
    ]
