# Generated by Django 4.2 on 2026-01-01 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_details_service_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Format: +221 77 123 45 67 ou 771234567', regex='^\\+?221?\\s?\\d{2}\\s?\\d{3}\\s?\\d{2}\\s?\\d{2}$')], verbose_name='Téléphone'),
        ),
    ]
