# Generated by Django 4.2 on 2026-01-01 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('appointment_type', models.CharField(choices=[('online', 'Consultation en ligne (Visio)'), ('in_person', 'Consultation en présentiel'), ('phone', 'Consultation téléphonique')], default='online', max_length=20, verbose_name='Type de consultation')),
                ('service_needed', models.CharField(choices=[('droit_famille', 'Droit de la famille'), ('droit_affaires', 'Droit des affaires'), ('droit_immobilier', 'Droit immobilier'), ('droit_successoral', 'Droit successoral'), ('droit_travail', 'Droit du travail'), ('autre', 'Autre')], max_length=50, verbose_name='Service demandé')),
                ('preferred_date', models.DateField(verbose_name='Date souhaitée')),
                ('preferred_time', models.TimeField(verbose_name='Heure souhaitée')),
                ('duration', models.IntegerField(default=60, help_text='Entre 30 et 180 minutes', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)], verbose_name='Durée estimée (minutes)')),
                ('description', models.TextField(help_text='Décrivez brièvement votre situation pour préparer la consultation', verbose_name='Description de votre situation')),
                ('documents', models.FileField(blank=True, null=True, upload_to='appointment_docs/', verbose_name='Documents joints')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=20, verbose_name='Statut')),
                ('confirmation_sent', models.BooleanField(default=False, verbose_name='Email de confirmation envoyé')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Rappel envoyé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['preferred_date', 'preferred_time'],
            },
        ),
    ]
